/**
 * Structured SVG Pinterest-style Eid card templates.
 * Each template maps to a layout component in StructuredLayouts.jsx.
 */

const TEMPLATES = [
  {
    id: 'classic-blue',
    name: 'Classic Blue',
    emoji: '🕌',
    description: 'Traditional Blue & Gold Motif',
    structured: true,
    layoutId: 'ClassicLayout',
    layoutProps: {
      bgColor: '#1a5c9e',
      patternColor: 'rgba(100,170,230,0.28)',
      archColor: '#f5f0dc',
      textColor: '#1a5099',
      accentColor: '#f0a500',
    },
    bg: { type: 'color', value: '#1a5c9e' },
    borderColor: '#f0a500',
  },
  {
    id: 'cosmic-purple',
    name: 'Cosmic Night',
    emoji: '🌌',
    description: 'Midnight Indigo with Glowing Stars',
    structured: true,
    layoutId: 'CosmicLayout',
    layoutProps: {
      accentColor: '#c084fc',
    },
    bg: { type: 'color', value: '#1e1060' },
    borderColor: '#c084fc',
  },
  {
    id: 'floral-vibrant',
    name: 'Vibrant Flora',
    emoji: '🌺',
    description: 'Colorful Sunset Floral',
    structured: true,
    layoutId: 'FloralLayout',
    layoutProps: {
      bgColor1: '#ffecd2',
      bgColor2: '#fcb69f',
      archColor: 'rgba(255, 255, 255, 0.92)',
      textColor: '#8b0000',
      accentColor: '#f43f5e',
    },
    bg: { type: 'gradient', value: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)' },
    borderColor: '#f43f5e',
  },
  {
    id: 'mandala-gold',
    name: 'Mandala Gold',
    emoji: '✨',
    description: 'Dark Obsidian with Gold Mandalas',
    structured: true,
    layoutId: 'MandalaLayout',
    layoutProps: {
      accentColor: '#facc15',
    },
    bg: { type: 'color', value: '#11100c' },
    borderColor: '#facc15',
  },
  {
    id: 'royal-emerald',
    name: 'Royal Emerald',
    emoji: '👑',
    description: 'Majestic Emerald & Gold Pattern',
    structured: true,
    layoutId: 'MajesticLayout',
    layoutProps: {
      bgColor: '#064e3b',
      archColor: '#ecfdf5',
      textColor: '#064e3b',
      accentColor: '#fbbf24',
    },
    bg: { type: 'color', value: '#064e3b' },
    borderColor: '#fbbf24',
  },
  {
    id: 'pearl-minimalist',
    name: 'Pearl Minimalist',
    emoji: '🕊️',
    description: 'Clean White & Slate Elegance',
    structured: true,
    layoutId: 'PearlLayout',
    layoutProps: {
      bgColor: '#f8fafc',
      textColor: '#334155',
      accentColor: '#94a3b8',
      highlightColor: '#cbd5e1',
    },
    bg: { type: 'color', value: '#f8fafc' },
    borderColor: '#94a3b8',
  },
  {
    id: 'sapphire-geometric',
    name: 'Sapphire Geometric',
    emoji: '💠',
    description: 'Modern Dark Blue Grid',
    structured: true,
    layoutId: 'SapphireLayout',
    layoutProps: {
      bgColor: '#0f172a',
      archColor: '#1e293b',
      textColor: '#e2e8f0',
      accentColor: '#38bdf8',
    },
    bg: { type: 'color', value: '#0f172a' },
    borderColor: '#38bdf8',
  },
  {
    id: 'pinterest-polaroid',
    name: 'Pastel Polaroid',
    emoji: '📸',
    description: 'Cute Washi Tape Photo Frame',
    structured: true,
    layoutId: 'PolaroidLayout',
    layoutProps: {},
    bg: { type: 'color', value: '#f4f0ea' },
    borderColor: '#e2a3b7',
  },
  {
    id: 'glass-dream',
    name: 'Glass Dream',
    emoji: '🔮',
    description: 'Vibrant Glassmorphism Orbs',
    structured: true,
    layoutId: 'GlassmorphismLayout',
    layoutProps: {},
    bg: { type: 'color', value: '#e0c3fc' },
    borderColor: '#ffffff',
  },
  {
    id: 'vintage-ticket',
    name: 'Vintage Boarding',
    emoji: '🎟️',
    description: 'Stately Classic Admit Ticket',
    structured: true,
    layoutId: 'VintageTicketLayout',
    layoutProps: {},
    bg: { type: 'color', value: '#fdfbf7' },
    borderColor: '#8c7a6b',
  }
];

export default TEMPLATES;
